
name: deploy-doc

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: setup node and pnpm
        uses: dafnik/setup-node-pnpm@v1
        with:
          pnpm: 8
          node: 18
          node-file: ''
          cwd: '.'
          install: false
          install-ignore-scripts: false

      - name: Build Project
        run: |
          npm install pnpm -g
          pnpm install
          pnpm run -r  --filter=doc build

      - name: Deploy to Github
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages 
          folder: site/doc/dist/